apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
  namaspace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: test-app
  template:
    metadata:
      labels:
        name: test-app
    spec:
      containers:
        - name: httpd
          image: balachandravk/cicd:v11.01
          ports:
            - containerPort: 8080



---

apiVersion: v1
kind: Service
metadata:
  name: test-svs
spec:
  type: NodePort
  selector:
    name: test-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
